config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :items
  resources :transactions, only: [:index]
  

  resources :categories do
    resources :items
  end
  
  resources :items do
    resources :transactions
  end
  
  root to: "reports#current"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_many :transactions
  validates :category_id, presence: true
  validates :name, presence: true

  after_initialize :init


  scope :with_balance, -> { joins(:transactions).select("items.*, sum(transactions.amount) as transactions_sum").group("items.id").order('items.name ASC') }

  def first_delivery_date
    deliveries = self.transactions.where(code: 'delivery').order('date ASC').limit(1)
    if !deliveries.empty?
      deliveries.first.date
    else
      nil
    end
  end

  def total_sales
    sales = -self.transactions.where(code: 'sale').sum(:amount)
  end

  def recent_sales
    sales = -self.transactions.where("code = ? AND date > ?", "sale", Date.today - 4.weeks).sum(:amount)
  end

  private

  def init
    self.discontinued  ||= false
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_category
  before_action :set_item, only: [:show, :edit, :update, :destroy, :delivery]

  # GET /items
  # GET /items.json
  def index
    if @category
      @items = @category.items
    else
      @items = Item.all.order('items.discontinued ASC').order('items.category_id ASC').order('items.name ASC')
    end
    @title = "Items"
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @transactions = @item.transactions.most_recent_first
    @balance = @item.transactions.sum(:amount)
    @title = @item.name
  end

  # GET /items/new
  def new
    @item = Item.new
    if @category
      @item.category_id = @category.id
    end
    @title = "New Item"
  end

  # GET /items/1/edit
  def edit
    @title = "Edit #{@item.name}"
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    if @category
      @item.category_id = @category.id
    end

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_category
      @category = params[:category_id] ? Category.find(params[:category_id]) : nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:category_id, :name, :description, :discontinued)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_category_form.html.erb
<%= simple_form_for [@category, @item] do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :category_id, as: :hidden %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :discontinued %>
  <%= f.button :submit %>
<% end %>

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.association :category %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :discontinued %>
  <%= f.button :submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>
<p>
  <em>Gray rows indicate a discontinued item.</em>
</p>

<p>
  <% if @category %>
    <%= link_to "New #{@category.name} Item", new_category_item_path(@category), class: "button button-new" %>
  <% else %>
    <%= link_to 'New Item', new_item_path, class: "button button-new" %>
  <% end %>
</p>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Category</th>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
    <% item.discontinued == true ? item_class = "discontinued" : item_class = "active" %>
      <tr class='<%= item_class %>'>
        <td><%= item.id %></td>
        <td><%= link_to item.category.name, item.category if item.category %></td>
        <td><%= link_to item.name, item %></td>
        <td><%= item.description %></td>
        <td>
          <%= link_to "Edit Item", edit_item_path(item), class: "button button-edit" %>
          <%= link_to "New Transaction", new_item_transaction_path(item), class: "button button-new" if item.discontinued == false %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<h1>New <%= @category ? @category.name : "item" %></h1>

<% if @category %>
  <%=  render 'category_form' %>
<% else %>
  <%= render 'form' %>
<% end %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Item: <%= @item.name %></h1>

<p>
  <strong>Category:</strong>
  <%= link_to @item.category.name, @item.category if @item.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Current Balance:</strong>
  <%= @balance %>
</p>
<hr />
<p>
  <strong>First Delivery Date:</strong>
  <%= @item.first_delivery_date %><br />
  <strong>Total Sales:</strong>
  <%= @item.total_sales %><br />
  <strong>Recent Sales:</strong>
  <%= @item.recent_sales %> in last four weeks<br />
  <strong>Weeks of stock:</strong>
  <% if @item.recent_sales == 0 %>
    "Not applicable."
  <% else %>
    <%= (@balance / (@item.recent_sales / 4.0)).round(1) %>
  <% end %>
</p>
<hr />
<p>
  <%= link_to "Edit #{@item.name}", edit_item_path(@item), class: "button button-edit" %>
  <%= link_to "New Transaction", new_item_transaction_path(@item), class: "button button-new" %>
</p>

<% if !@transactions.blank? %>
  <table>
    <tr>
      <th>Id</th>
      <th>Date</th>
      <th>Code</th>
      <th>Item</th>
      <th>Amount</th>
      <th>Action</th>
    </tr>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.id %></td>
        <td><%= transaction.date %></td>
        <td><%= transaction.code %></td>
        <td><%= transaction.item.name %></td>
        <td><%= transaction.amount %></td>
        <td>
          <%= link_to "Edit", edit_item_transaction_path(transaction.item, transaction), class: "button button-edit" %>
          <%= link_to 'Delete', [transaction.item, transaction], method: :delete, class: 'button button-delete', data: { confirm: 'Are you sure?'} if transaction.item.id %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>