config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :items
  resources :transactions, only: [:index]
  

  resources :categories do
    resources :items
  end
  
  resources :items do
    resources :transactions
  end
  
  root to: "reports#current"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @title = "Categories"
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @items = @category.items.order(:discontinued).order(:name)
    @title = @category.name
  end

  # GET /categories/new
  def new
    @category = Category.new
    @title = "New Category"
  end

  # GET /categories/1/edit
  def edit
    @title = "Edit #{@category.name}"
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<p>
  <%= link_to 'New Category', new_category_path, class: "button button-new" %>
</p>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= link_to category.name, category %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class: "button button-edit" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Category: <%= @category.name %>
</h1>

<p>
  <%= link_to 'Edit Category', edit_category_path(@category), class: "button button-edit" %>
  <%= link_to "New #{@category.name}", new_category_item_path(@category), class: "button button-new" %>
</p>

<p>
  <em>Gray rows indicate a discontinued item.</em>
</p>

<% if !@items.blank? %>
  <table>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
    <% @items.each do |item| %>
    <% item.discontinued == true ? item_class = "discontinued" : item_class = "active" %>
      <tr class='<%= item_class %>'>
        <td><%= item.id %></td>
        <td><%= link_to item.name, item %></td>
        <td><%= item.description %></td>
        <td>
          <%= link_to "Edit Item", edit_item_path(item), class: "button button-edit" %>
          <%= link_to "New Transaction", new_item_transaction_path(item), class: "button button-new" if item.discontinued == false %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>